--CONSULTANDO TODOS OS REGISTROS DA TABELA DE VENDEDORES
SELECT * FROM tabela_de_vendedores;

--CONSULTA AGRUPANDO A QUANTIDADE DE VENDAS POR VENDEDORES USANDO O GROUP BY
SELECT MATRICULA AS VENDEDOR, COUNT(NUMERO) AS QTD_VENDAS 
FROM NOTAS_FISCAIS 
GROUP BY MATRICULA;


--CONSULTA AGRUPANDO O RESULTADO DA QUANTIDADE DE VENDAS FEITAS POR CLIENTE USANDO GROUP BY
SELECT CPF AS CLIENTE, COUNT(NUMERO) AS VENDAS 
FROM NOTAS_FISCAIS 
GROUP BY CPF;