--FUNCOES DE STRING
--CONVERTENDO A STRING PARA MINUSCULA USANDO LOWER
SELECT NOME, LOWER(NOME) FROM TABELA_DE_CLIENTES;

--CONVERTENDO A STRING PARA MINUSCULO UPPER
SELECT NOME, UPPER(NOME) FROM TABELA_DE_CLIENTES;


--CONCATENANDO STRING
SELECT NOME,ENDERECO_1 ||  '' || BAIRRO || ' ' || CIDADE || ''|| ESTADO AS ENDERECO_COMPLETO
FROM TABELA_DE_CLIENTES; 





--FUNCOES DE DATA
SELECT SYSDATE FROM DUAL;


SELECT  TO_CHAR(SYSDATE, 'DD/MM/YYYY' ) FROM DUAL;

SELECT NOME, MONTHS_BETWEEN (SYSDATE, DATA_DE_NASCIMENTO)/12 AS IDADE
FROM tabela_de_clientes
