/*Continuacao script*/

/*ADICIONANDO REGISTRO A TB_CLIENTES*/
INSERT INTO tb_clientes 
(CPF,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA,DT_NASCIMENTO)
VALUES
('11642432418','EDUARDO','RUA MACEDO','CRISTO REDENTOR','JOAO PESSOA','PB','58050220',23,'F',2000.000,20,0,TO_DATE('05/04/1998','DD/MM/YYYY'));


/*CONSULTANDO A TABELA CLIENTES*/
SELECT * FROM tb_clientes;

/*INCLUINDO NOVOS CAMPOS A TABELA VENDEDORES*/
ALTER TABLE tb_vendedores ADD  DATA_ADMISSAO DATE;
ALTER TABLE tb_vendedores ADD DE_FERIAS NUMBER(1,0);

/*ADICIONANDO A CHAVE PRIMARIA A TABELA VENDEDORES*/
ALTER TABLE tb_vendedores ADD CONSTRAINT PK_TB_VENDEDORES PRIMARY KEY (MATRICULA);

/*LIMPANDO OS REGISTROS DA TABELA VENDEDORES PARA NOVA INSERÇÃO*/

DELETE FROM tb_vendedores;

/*INSERINDO REGISTRO NA TABELA VENDEDORES COM OS NOVOS CAMPS ADICIONADOS*/
INSERT INTO tb_vendedores 
(MATRICULA, NOME, PERCENTUAL_COMISSAO,DATA_ADMISSAO, DE_FERIAS)
VALUES
('00235','CLAUDIO SILVA',0.9,TO_DATE('04/10/2020','DD/MM/YYYY'),0);

INSERT INTO tb_vendedores 
(MATRICULA, NOME, PERCENTUAL_COMISSAO,DATA_ADMISSAO, DE_FERIAS)
VALUES
('00236','AMADOR AMARAL',0.7,TO_DATE('05/01/2001','DD/MM/YYYY'),0);

INSERT INTO tb_vendedores 
(MATRICULA, NOME, PERCENTUAL_COMISSAO,DATA_ADMISSAO, DE_FERIAS)
VALUES
('00237','BIANCA',0.6,TO_DATE('08/05/2015','DD/MM/YYYY'),1);

INSERT INTO tb_vendedores 
(MATRICULA, NOME, PERCENTUAL_COMISSAO,DATA_ADMISSAO, DE_FERIAS)
VALUES
('00238','LUIZA SOUSA',0.9,TO_DATE('10/12/2020','DD/MM/YYYY'),1);


/*CONSULTANDO A TABELA DE VENDEDORES*/
SELECT * FROM tb_vendedores;

/*CONSULTANDO A TABELA DE PRODUTOS*/
SELECT * FROM tb_produtos;

/*CONSULTANDO TABELA DE CLIENTES*/
SELECT * FROM tb_clientes;
