
/*CRIANDO A TABELA CLIENTE DO CURSO*/
CREATE TABLE tb_clientes (
    CPF VARCHAR(11),
    NOME VARCHAR(100),
    DT_NASCIMENTO DATE,
    ENDERECO VARCHAR(150),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(2),
    CEP VARCHAR(8),
    IDADE INT, 
    SEXO VARCHAR(1),
    LIMITE_CREDITO FLOAT,
    VOLUME_COMPRA FLOAT,
    PRIMEIRA_COMPRA NUMBER(1));
    
    
    
/*CRIANDO A TABELA DE VENDEDORES DO CURSO*/    
CREATE TABLE tb_vendedores
(   MATRICULA VARCHAR(5),
    NOME VARCHAR(100),
    PERCENTUAL_COMISSAO FLOAT
    );
    
 /*ALTERANDO A TABELA VENDEDORES PARA ADICIONAR A CHAVE PRIMARIA*/   
 ALTER TABLE tb_vendedores ADD CONSTRAINT pk_tb_vendedores PRIMARY KEY (MATRICULA );
 
 
 
/*CRIANDO TABELA DE PRODUTOS*/
  CREATE TABLE TB_PRODUTOS
   (    PRODUTO VARCHAR2(20 BYTE), 
        NOME VARCHAR2(150 BYTE), 
        EMBALAGEM VARCHAR2(50 BYTE), 
        TAMANHO VARCHAR2(50 BYTE), 
        SABOR VARCHAR2(50 BYTE), 
        PRECO_LISTA FLOAT(126)
   );
 
 
 /*DROPANDO A TABELA DE TESTE*/
 DROP TABLE tb_clientes2;
 DROP TABLE tb_clientes3;
 
 
 
/*INSERINDO REGISTROS NA TABELA PRODUTO*/
 INSERT INTO tb_produtos
 (PRODUTO, NOME, EMBALAGEM,TAMANHO, SABOR, PRECO_LISTA)
 VALUES
 ('1040107','LIGHT  - 350 ML - MELANCIA','LATA','350 ML','MELANICA',4.56);
 
 
 /*CONSULTANDO A TABELA PRODUTO*/
 SELECT * FROM tb_produtos;
 
 
 /*INSERINDO VENDEDORES NA TTABELA*/
 INSERT INTO tb_vendedores
 (MATRICULA, NOME, PERCENTUAL_COMISSAO)
 VALUES
 ('00233','JOSE GERALDO DA FONSECA',0.10);
 
 /*CONSULTANDO A TABELA VENDEDORES*/
 SELECT * FROM tb_vendedores;
 
 
 /*INSERINDO VARIOS REGISTROS NA TABELA DE PRODUTOS*/
  INSERT INTO tb_produtos
 (PRODUTO, NOME, EMBALAGEM,TAMANHO, SABOR, PRECO_LISTA)
 VALUES
 ('1037797','CLEAN  - 2 LITROS - LARANJA','PET','2 LITROS','LARANJA',16.01);
 
  INSERT INTO tb_produtos
 (PRODUTO, NOME, EMBALAGEM,TAMANHO, SABOR, PRECO_LISTA)
 VALUES
 ('1000889','SABOR DA MONTANHA  - 700 ML - UVA','GARRAFA','700 ML','UVA',6.31);
 
  INSERT INTO tb_produtos
 (PRODUTO, NOME, EMBALAGEM,TAMANHO, SABOR, PRECO_LISTA)
 VALUES
 ('1004327','VIDREIRA DO CAMPO  - 1,5 LITROS - MELANCIA','PET','1,5 LITROS','MELANICA',19.51);
 
   INSERT INTO tb_produtos
 (PRODUTO, NOME, EMBALAGEM,TAMANHO, SABOR, PRECO_LISTA)
 VALUES
 ('544931','FRESCOR DO VERAO  - 470 ML - MANGA','PET','470 ML','MANGA',3.20);
 
 /*CONSULTANDO A TABELA DE PRODUTOS*/
 SELECT * FROM tb_produtos;
 
 
 /*CRIANDO MAIS VENDEDORES*/
 INSERT INTO tb_vendedores
 (MATRICULA, NOME, PERCENTUAL_COMISSAO)
 VALUES
 ('00235','MARCIO ALMEIDA SILVA',0.8);
 
 INSERT INTO tb_vendedores
 (MATRICULA, NOME, PERCENTUAL_COMISSAO)
 VALUES
 ('00236','CLAUDIA MORAIS',0.8);
 
 /*CONSULTANDO A TABELA DE VENDEDORES*/
 SELECT * FROM tb_vendedores;
 
 
 /*ALTERANDO CAMPOS NA TABELA COM UPDATE*/
 UPDATE tb_produtos 
 SET EMBALAGEM = 'LATA', PRECO_LISTA = 2.46
 WHERE PRODUTO= 544931;
 
 UPDATE tb_vendedores
 SET PERCENTUAL_COMISSAO = 0.8
 WHERE MATRICULA = 00233;
 
 UPDATE tb_vendedores
 SET NOME = 'JOSE GERALDO DA FONSECA JUNIOR'
 WHERE MATRICULA = 00233;
 
 
 
/*APAGANDO REGISTRO DA TABELA*/
DELETE FROM tb_produtos WHERE PRODUTO = '544931';

DELETE FROM tb_vendedores WHERE MATRICULA = '00233';
 
 
/*ADICIONANDO CHAVE PRIMARIA A TABELA*/
ALTER TABLE tb_produtos ADD CONSTRAINT PK_TB_PRODUTOS PRIMARY KEY (PRODUTO);
 