--CRIANDO AS TABELAS DO ESQUEMA ORA_HOMOLOGACAO

--DROPANDO AS TABELAS ANTIGAS
DROP TABLE ITEMS_NOTAS_FISCAIS;
DROP TABLE NOTAS_FISCAIS;
DROP TABLE TABELA_DE_CLIENTES;
DROP TABLE TABELA_DE_PRODUTOS;
DROP TABLE TABELA_DE_VENDEDORES;



--CRIANDO TABELA CLIENTES
CREATE TABLE TABELA_DE_CLIENTES
(   CPF VARCHAR2(12) NOT NULL,
    NOME VARCHAR2(100) NULL,
    ENDERECO VARCHAR2(150) NULL,
    BAIRRO VARCHAR2(50) NULL,
    CIDADE VARCHAR2(50) NULL,
    ESTADO VARCHAR2(50) NULL,
    CEP VARCHAR2(8) NULL,
    DATA_DE_NASCIMENTO DATE NULL,
    IDADE INTEGER NULL,
    SEXO VARCHAR2(1) NULL,
    LIMITE_DE_CREDITO FLOAT NULL,
    VOLUME_DE_COMPRA FLOAT NULL,
    PRIMEIRA_COMPRA NUMBER(2)
    );


    --ALTERANDO A TABELA PARA INCLUSAO DA CHAVE PRIMARIA/CONSTRAINTS 
ALTER TABLE tabela_de_clientes ADD CONSTRAINT PK_TABELA_DE_CLIENTES PRIMARY KEY (CPF);

    

    --CRIANDO TABELA PRODUTOS
CREATE TABLE TABELA_DE_PRODUTOS
    (   CODIGO_DO_PRODUTO VARCHAR2(11) NOT NULL,
        NOME_DO_PRODUTO VARCHAR2(50) NULL,
        EMBALAGEM VARCHAR2(20) NULL,
        TAMANHO VARCHAR2(10) NULL,
        SABOR VARCHAR2(20) NULL,
        PRECP_DE_LISTA FLOAT NOT NULL
        );


    --ALTERANDO A TABELA PARA INCLUSAO DA CHAVE PRIMARIA
ALTER TABLE TABELA_DE_PRODUTOS ADD CONSTRAINT PK_TABELA_DE_PRODUTOS PRIMARY KEY (CODIGO_DO_PRODUTO);   

   
    --CRIANDO TABELA NOTAS_FISCAIS
CREATE TABLE TABELA_DE_VENDEDORES
   (   MATRICULA VARCHAR2(10) NOT NULL,
       NOME VARCHAR2(5) NULL,
       PERCENTUAL_COMISSAO FLOAT NULL,
       DATA_ADMISSAO DATE NULL,
       DE_FERIAS NUMBER(1,0) 
       BAIRRO VARCHAR2(50) NULL
   );

    --ALTERANDO A TABELA PARA INCLUSAO DA CHAVE PRIMARIA
 ALTER TABLE TABELA_DE_VENDEDORES ADD CONSTRAINT PK_TABELA_DE_VENDEDORES PRIMARY KEY (MATRICULA);


    --CRIANDO TABELA DE NOTAS FISCAIS/VENDAS
CREATE TABLE NOTAS_FISCAIS
    (  CPF VARCHAR2(12) NOT NULL,
       MATRICULA VARCHAR2(10) NOT NULL,
       DATA_VENDA DATE NULL,
       NUMERO INTEGER NOT NULL,
       IMPOSTO FLOAT NOT NULL
   );


    --ALTERANDO A TABELA PARA INCLUSAO DA CHAVE PRIMARIA
ALTER TABLE NOTAS_FISCAIS ADD CONSTRAINT PK_NOTAS_FISCAIS PRIMARY KEY (NUMERO);

    --ALTERANDO A TABELA PARA INCLUSAO DA CHAVE ESTRANGEIRA 
ALTER TABLE NOTAS_FISCAIS ADD CONSTRAINT FK_NOTAS_FISCAIS1 FOREIGN KEY (MATRICULA) REFERENCES TABELA_DE_VENDEDORES (MATRICULA);
ALTER TABLE NOTAS_FISCAIS ADD CONSTRAINT FK_NOTAS_FISCAIS2 FOREIGN KEY (CPF) REFERENCES TABELA_DE_CLIENTES (CPF);



    --CRIANDO TABELA ITENS_NOTAS_FISCAIS
CREATE TABLE ITENS_NOTAS_FISCAIS
(
    NUMERO INTEGER NOT NULL,
    CODIGO_DO_PRODUTO VARCHAR2(10) NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    PRECO FLOAT NOT NULL
);


    --ALTERANDO A TABELA PARA INCLUSAO DA CHAVE PRIMARIA/ESTRANGEIRA
ALTER TABLE ITENS_NOTAS_FISCAIS ADD CONSTRAINT PK_ITENS_NOTAS_FISCAIS PRIMARY KEY (NUMERO, CODIGO_DO_PRODUTO);

ALTER TABLE ITENS_NOTAS_FISCAISADD CONSTRAINT FK_ITENS_NOTAS_FISCAIS1 FOREIGN KEY (CODIGO_DO_PRODUTO) REFERENCES TABELA_DE_PRODUTOS (CODIGO_DO_PRODUTO);

ALTER TABLE ITENS_NOTAS_FISCAIS ADD CONSTRAINT FK_ITENS_NOTAS_FISCAIS2 FOREIGN KEY (NUMERO) REFERENCES NOTAS_FISCAIS (NUMERO);