/*CRIANDO O BANCO DE DADOS CHAMADO BANCO*/
CREATE DATABASE banco;

/*INFOMRANDO QUE VAMOS UTILIZAR(DIZENDO QUE É O BANCO PRINCIPAL) O BANCO DEPOIS DE CRIADO*/
USE banco;

/*VISUALZIANDO O BANCO CRIADO */
SHOW DATABASES;

/*CRIANDO A TABELA DO BANCO E DEFININADO CAMPOS(COLUNAS) COM SEUS TIPOS DE DADOS E CONSTRAINTS */
CREATE TABLE contas
( 	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	nome VARCHAR(100), 
    sobrenome VARCHAR(100),
    saldo FLOAT,
    data_nascimento DATE
);

/*VISUALIZANDO TABELAS DO BANCO*/
SHOW TABLES;

/*CRIANDO INDICE(INDEX) NA TABELA PARA DEIXAR AS CONSULTAS(SELECTS COM WHERE) MAIS RAPIDA*/
CREATE INDEX index_saldo 
ON contas(saldo);


/*ADICIONANDO REGISTROS NA TABELA
PODEMOS INSERIR SEM INFORMAR OS CAMPOS DA TABELA JÁ QUE TEMOS CONSTRAINTS*/
INSERT INTO contas(nome,sobrenome, saldo, data_nascimento) VALUES ("Luci", "Sousa",1000,"1998-04-05" );
INSERT INTO contas(nome,sobrenome, saldo, data_nascimento) VALUES ("Teste", "Empresa",10000,"1980-08-06" );
INSERT INTO contas(nome,sobrenome, saldo, data_nascimento) VALUES ("Lex", "Luthor",1000,"1970-04-03");

/*CONSULTANDO A TABELA*/
SELECT * FROM contas;
