--uma função dentro de uma procedure

create or replace PROCEDURE INCLUIR_CLIENTE
(   p_ID IN CLIENTE.ID%TYPE,
    p_RAZAO_SOCIAL IN CLIENTE.RAZAO_SOCIAL%TYPE,
    p_CNPJ IN CLIENTE.CNPJ%TYPE,
    p_SEGMERCAD0_ID IN CLIENTE.SEGMERCADO_ID%TYPE,
    p_DATA_INCLUSAO IN CLIENTE.DATA_INCLUSAO%TYPE,
    p_FATURAMENTO_PREVISTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE,
    p_CATEGORIA IN CLIENTE.CATEGORIA%TYPE
    )
IS
    v_CATEGORIA cliente.categoria%type; --variavel
    
BEGIN
    
    v_CATEGORIA := categoria_cliente(p_FATURAMENTO_PREVISTO); --funcao

    INSERT INTO CLIENTE (ID, RAZAO_SOCIAL, CNPJ, SEGMERCADO_ID , DATA_INCLUSAO, FATURAMENTO_PREVISTO, CATEGORIA) VALUES (p_ID, p_RAZAO_SOCIAL, p_CNPJ, p_SEGMERCAD0_ID,SYSDATE, p_FATURAMENTO_PREVISTO, p_CATEGORIA );

    COMMIT;

END;





--FUNCAO/PROCEDURE
create or replace NONEDITIONABLE PROCEDURE incluir_cliente (
    p_ID IN CLIENTE.ID%type, 
    p_RAZAO_SOCIAL IN CLIENTE.RAZAO_SOCIAL%type,
    p_CNPJ IN CLIENTE.CNPJ%type, 
    p_SEGMERCADO_ID IN CLIENTE.SEGMERCADO_ID%type,
    p_FATURAMENTO_PREVISTO IN CLIENTE.FATURAMENTO_PREVISTO%type
)
IS
    v_CATEGORIA CLIENTE.CATEGORIA%type;
    v_CNPJ CLIENTE.CNPJ%type := p_CNPJ;
BEGIN
    formata_cnpj(v_CNPJ);
    v_CATEGORIA := categoria_cliente(p_FATURAMENTO_PREVISTO);
    INSERT INTO CLIENTE (ID, RAZAO_SOCIAL, CNPJ, SEGMERCADO_ID, DATA_INCLUSAO, FATURAMENTO_PREVISTO, CATEGORIA)
    VALUES (p_ID, p_RAZAO_SOCIAL, v_CNPJ, p_SEGMERCADO_ID, SYSDATE, p_FATURAMENTO_PREVISTO, v_CATEGORIA);
    COMMIT;
END;