--CURSOR É UMA ESTRUTUEA IMPLEMENTADA NO ORACLE QUE PERMITE UMA INTERATIVIDADE LINHA A LINHA ATRAVES
--DE UMA DETERMINADA ORDEM.

--FASES PARA USO DO CURSOS
--DELCARAÇÃO: ONDE DEFINIMOS QUAL CONSULTA SQL ESTARA SENDO CARREGADA AO CURSOS;
--ABERTURA: ABRIMOS O CURSOR PARA PERCORRE-LO LINHA A LINHA;
--PERCORRE LINHA A LINHA ATE O SEU FINAL;
--FECHA O CURSOS;

--FETCH REALIZA A LEITURA DE CADA LINHA DO CURSOR


DECLARE
    CURSOR cur_CLIENTE IS SELECT ID, RAZAO_SOCIAL FROM CLIENTE;
    v_ID CLIENTE.ID%type;
    v_RAZAO_SOCIAL CLIENTE.RAZAO_SOCIAL%type;
BEGIN
    OPEN cur_CLIENTE; --ABRE O CURSOR
    LOOP
        FETCH cur_CLIENTE INTO v_ID, v_RAZAO_SOCIAL; --PERCORRE LINHA A LINHA
    EXIT WHEN cur_CLIENTE%NOTFOUND;
        dbms_output.put_line('ID = ' || v_ID);
        dbms_output.put_line('Razão Social = ' || v_RAZAO_SOCIAL);
    END LOOP;
    CLOSE cur_CLIENTE; --FECHA O CURSOR
END;



--CURSOR COM FOR
DECLARE
    CURSOR cur_CLIENTE IS SELECT ID FROM CLIENTE;
    v_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%type := 1;
BEGIN
    FOR cli_rec IN cur_CLIENTE LOOP
        atualizar_cli_seg_mercado(p_SEGMERCADO_ID => v_SEGMERCADO_ID, p_ID => cli_rec.ID);
    END LOOP;
END;