--CRIA VARIAVEL DE SESSAO PARA EXECUTAR VÁRIAS SESSÕES
ALTER SESSION SET "_oracle_script"=true; 

--CRIANDO USUARIOS E LIBERANDO PRIVILEGIOS E ATRIBUIÇÕES NO ORACLE
--CRIANDO USUARIO:
CREATE USER teste_homologacao IDENTIFIED BY homo123 DEFAULT TABLESPACE users;

--Crinado permissao SUPER
GRANT ALL PRIVILEGES TO teste_homologacao;
ALTER USER teste_homologacao QUOTA UNLIMITED ON USERS;

--Criando permissao/privilegios simples ao usuario
GRANT CREATE SESSION TO teste_homologacao;

--Criando permissao /privilegios
GRANT CONNECT, RESOURCE TO teste_homologacao;

--Removendo/Revogando as permissoes/privilegiosdo usuario 
REVOKE CONNECT, RESOURCE FROM teste_homologacao;
REVOKE CREATE VIEW FROM teste_homologacao;

--Dropando usuario
DROP USER homologacao CASCADE;

--ALTERANDO A SENHA, BLOQUEANDO/DESBLOQUEANDO E EXCLUINDO USUARIOS
--ALTERANDO SENHA:
ALTER USER teste_homologacao IDENTIFIED by 123;

--BLOQUEANDO USUARIO:
ALTER USER teste_homologacao ACCOUNT LOCK;

--DESBLOQUEANDO USUARIO:
ALTER USER teste_homologacao ACCOUNT UNLOCK;


--PRIVILEGIOS DE SISTEMA
--SÃO PRIVILEGIOS QUE PERMITE EXECUTAR INSTRUÇÕES DDL, COMO CREATE SESSION, CREATE TABLE , CREATE VIEW

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO teste_homologacao;


--PRIVILEGIOS DE OBJETO
--SÃO PRIVILEGIOS QUE PERMITEM EXECUTAR INSTRUÇÕES DML, SELECT, INSERT, UPDATE E DELETE

GRANT SELECT, UPDATE ON teste.tes TO teste_homologacao;
