--Inserindo dados com INSERT/ INSERT ALL

INSERT INTO PRODUTOS(CODIGO_PRODUTO,DESCRICAO,SABOR,TAMANHO,EMBALAGEM,PRECO_LIST)
VALUES('104020','SUCO - 310 ml','LARANJA','310 ml','LATA',5.5);

--INSERINDO VARIOS REGISTRO COM INSERT ALL
INSERT ALL
INTO PRODUTOS(CODIGO_PRODUTO,DESCRICAO,SABOR,TAMANHO,EMBALAGEM,PRECO_LIST)
VALUES('104030','REFRIGERANTE - 1LT','COCA COLA','1 LT','GARRAFA',8.5)
INTO PRODUTOS(CODIGO_PRODUTO,DESCRICAO,SABOR,TAMANHO,EMBALAGEM,PRECO_LIST)
VALUES('104040','SUCO - 310 ml','LIMAO','310 ml','LATA',5.5)
SELECT * FROM DUAL;


--INSERINDO REGISTRO SEM DEFINIR OS CAMPOS APENAS SEGUINDO A SEQUENCIA DOS CAMPOS DA TABELA
INSERT INTO PRODUTOS VALUES('104050','AGUA MINERAL- 500 ml','AGUA','500 ml','GARRAFA',2.5);



INSERT INTO CLIENTE(CPF,NOME, ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA)
VALUES('1478662710','Érica Carvalho','R. Iriquitia','Jardins','São Paulo','SP','80012212',TO_DATE('01/09/1990','DD/MM/YYYY'),'27','F',170000,2400,0);




--INSERINDO REGISTRO A PARTIR DE OUTRA TABELA: COMO NÃO EXISTIA A TABELA QUE CONTINHAM OS DADOS COM OS REGISTROS PARA REALIZAR A INSERÇÃO A PARTIR DELA, ENTÃO, CRIEI A TABELA TABELA_DE_PRODUTOS E FIZ O INSERT COM OS REGISTROS E REALIZEI A IMPORTAÇÃO ATRAVES DO SQLPLUS.

--INSERINDO REGISTRO A PARTIR DE OUTRA TABELA
INSERT INTO PRODUTOS
SELECT CODIGO_DO_PRODUTO AS CODIGO_PRODUTO , NOME_DO_PRODUTO AS DESCRICAO, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA
FROM TABELA_DE_PRODUTOS;


--FAZENDO O MESMO PROCEDIMENTO USADO NO EXEMPLO ACIMA
--INSERINDO REGISTRO A PARTIR DE UMA TABELA
INSERT INTO CLIENTE (CPF, NOME, CEP, ENDERECO, BAIRRO, CIDADE, ESTADO, DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA)
SELECT CPF, NOME, CEP, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,idade, sexo, limite_de_credito AS LIMITE_CREDITO, volume_de_compra AS VOLUME_COMPRA, primeira_compra 
from tabela_de_clientes;

