--Procedimentos de PRIVILEGES e criação do PACKAGE

-- 1-CRIAR O SPEC(PACKAGE SPEC);
-- 2-CRIAR O BODY(PACKAGE BODY);
-- 3-APLICAR PERMISSÃO PARA O USUARIO ENXERGAR O PACOTE;
-- 4-CRIAR SYNONYM PARA TER ACESSO AO SCHEMA;

-- PERMISSÃO
GRANT EXECUTE ON CLIENTE_PAC TO user_app;
-- SYNONYM
CREATE PUBLIC SYNONYM CLIENTE_PAC FOR user_dev.CLIENTE_PAC;