--Sinonimos e Dependencias
--Packages


--SYNONYM PRIVADO
CREATE OR REPLACE SYNONYM <SYNONYM_NAME> FOR <OBJECT_NAME>; --CRIA

DROP SYNONYM <SYNONYM_NAME>; --DROP


 --SYNONYM PUBLIC       
CREATE OR REPLACE PUBLIC SYNONYM <SYNONYM_NAME> FOR <OBJECT_NAME>; --CRIA

DROP PUBLIC SYNONYM <SYNONYM_NAME>; --DROP


